language: rust
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - nightly

after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
