[package]
name = "plasmodesmata"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
bytes = "0.4"
rustls = "0.9"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-rustls = "0.2"